### ISSUE TITLE
Post a question

### ISSUE THREAD

**Issue by shinjia305** [shinjia305/holdem-qa#12]
## Outline
#2 

## ToDo

- [ ] Allows to post a question
- [ ] if logged in, you can post a question
- [ ] if not logged in, you cannot post it
- [ ] Use rich text (Markdown and so on...)
